apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webapp
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: webapp
        env:
        - name: ENV
          value: "development"

