configMapGenerator:
- literals:
  - ENV=production
  name: app-config
secretGenerator:
- literals:
  - DB_PASSWORD=prodsecret
  name: db-secret
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: deployment-patch.yaml
