apiVersion: builtin
kind: LabelTransformer
metadata:
  name: labels
labels:
  team: devops
  project: kustomize-capstone
fieldSpecs:
  - path: metadata/labels
    create: true
  - path: spec/template/metadata/labels
    create: true

